### ISSUE TITLE
Cannot read property 'fata' of undefined

### ISSUE THREAD

**Issue by Zambonilli** [silas/hapi-bunyan#3]
Running into an unhandled error with logging POST requests with a JSON body.  It looks like the makeCtx method is checking for the existence of properties on a tags variable that is undefined on line 75.  I'm using hapi@8.0.0 and hapi-bunyan@0.4.1 and am using the default configuration for both hapi, hapi-bunyan and bunyan.

I can fork and add if tags && tags.fatal to the various if statements if you want.

**Comment by silas** [comment]
Should be fixed in 0.4.2 , thanks for reporting!

Let me know if you run into other issues.

**Comment by Zambonilli** [comment]
no problem.  Thanks for the quick fix!
