### ISSUE TITLE
Wrap `data` coming from `request-error`?

### ISSUE THREAD

**Issue by dschenkelman** [silas/hapi-bunyan#6]
Logging via [`request-error`](https://github.com/silas/hapi-bunyan/blob/master/lib/index.js#L150) receives `data` without a nested `data` property. This results in empty messages because of [this check](https://github.com/silas/hapi-bunyan/blob/master/lib/index.js#L31).

Is the recommended approach to wrap it in [`handler`](https://github.com/silas/hapi-bunyan/blob/master/lib/index.js#L154) in this case or should I send a PR to automatically wrap this?

**Comment by dschenkelman** [comment]
I'd change this line [here](https://github.com/silas/hapi-bunyan/blob/master/lib/index.js#L158) to:
```
if (data.data){ return logEvent(ctx, data, request) }
logEvent(ctx, data.data, request);
```

Wrapping it in `handler` can incorrectly generate a circular reference.

**Comment by silas** [comment]
I'd been meaning to special case that error, bunyan has native support for rendering errors. I updated the plugin to just call bunyan with the proper method signature.

`request-error` will now result in something like

```
{ name: 'test',
  hostname: 'air.local',
  pid: 3702,
  req_id: '1426753408117:air.local:3702:i7fw53e7:10000',
  level: 50,
  err:
   { message: 'Uncaught error: fail',
     name: 'Error',
     stack: 'Error: Uncaught error: fail\n    at ...' },
  msg: 'Uncaught error: fail',
  time: '2015-03-19T08:23:28.124Z',
  v: 0 }
```

I also exposed the `logEvent` function, so if you want to completely rewrite `data` you can do something like:

``` javascript
var hapiBunyan = require('hapi-bunyan');

function handler(eventType, request, err, tags) {
  if (eventType === 'request-error') {
    hapiBunyan.log(this, { hello: 'world' }, request);
    return true;
  }
}
```

**Comment by dschenkelman** [comment]
Nice! Thanks for the quick response also :)
